In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Logistic Regression

In [5]:
from sklearn.linear_model import LogisticRegression
log_clf = LogisticRegression()
log_clf.fit(X_train,y_train)

LogisticRegression()

In [6]:
log_clf.predict(sc.transform([[8,10,10,8,7,10,9,7,1]]))

array([4], dtype=int64)

In [7]:
from sklearn.metrics import confusion_matrix,accuracy_score
log_cm = confusion_matrix(y_test,log_clf.predict(X_test))
log_acc = accuracy_score(y_test,log_clf.predict(X_test))
print(log_cm)
print("Accuracy Score:",log_acc)

[[103   4]
 [  5  59]]
Accuracy Score: 0.9473684210526315


## K-Nearest Neighbors

In [8]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn_clf.fit(X_train,y_train)

KNeighborsClassifier()

In [9]:
knn_clf.predict(sc.transform([[8,10,10,8,7,10,9,7,1]]))

C:\Users\Awais Tanveer Khan\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([4], dtype=int64)

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score
knn_cm = confusion_matrix(y_test,knn_clf.predict(X_test))
knn_acc = accuracy_score(y_test,knn_clf.predict(X_test))
print(knn_cm)
print("Accuracy Score:",knn_acc)

[[103   4]
 [  5  59]]
Accuracy Score: 0.9473684210526315


C:\Users\Awais Tanveer Khan\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\Awais Tanveer Khan\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer

## Support Vector Machine

In [11]:
from sklearn.svm import SVC
svc_clf = SVC(kernel='linear',random_state=0)
svc_clf.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [12]:
svc_clf.predict(sc.transform([[8,10,10,8,7,10,9,7,1]]))

array([4], dtype=int64)

In [13]:
from sklearn.metrics import confusion_matrix,accuracy_score
svc_cm = confusion_matrix(y_test,svc_clf.predict(X_test))
svc_acc = accuracy_score(y_test,svc_clf.predict(X_test))
print(svc_cm)
print("Accuracy Score:",svc_acc)

[[102   5]
 [  5  59]]
Accuracy Score: 0.9415204678362573


## Kernel SVM

In [14]:
from sklearn.svm import SVC
ker_clf = SVC(kernel='rbf',random_state=0)
ker_clf.fit(X_train,y_train)

SVC(random_state=0)

In [15]:
ker_clf.predict(sc.transform([[8,10,10,8,7,10,9,7,1]]))

array([4], dtype=int64)

In [16]:
from sklearn.metrics import confusion_matrix,accuracy_score
ker_cm = confusion_matrix(y_test,ker_clf.predict(X_test))
ker_acc = accuracy_score(y_test,ker_clf.predict(X_test))
print(ker_cm)
print("Accuracy Score:",ker_acc)

[[101   6]
 [  3  61]]
Accuracy Score: 0.9473684210526315


## Naive Bayes

In [17]:
from sklearn.naive_bayes import GaussianNB
nb_clf = GaussianNB()
nb_clf.fit(X_train,y_train)

GaussianNB()

In [18]:
nb_clf.predict(sc.transform([[8,10,10,8,7,10,9,7,1]]))

array([4], dtype=int64)

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
nb_cm = confusion_matrix(y_test,nb_clf.predict(X_test))
nb_acc = accuracy_score(y_test,nb_clf.predict(X_test))
print(nb_cm)
print("Accuracy Score:",nb_acc)

[[99  8]
 [ 2 62]]
Accuracy Score: 0.9415204678362573


## Decision Tree Classification (Best For This Breast Cancer Study)

In [20]:
from sklearn.tree import DecisionTreeClassifier
dt_clf = DecisionTreeClassifier(criterion='entropy',random_state=0)
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [21]:
dt_clf.predict(sc.transform([[8,10,10,8,7,10,9,7,1]]))

array([4], dtype=int64)

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score
dt_cm = confusion_matrix(y_test,dt_clf.predict(X_test))
dt_acc = accuracy_score(y_test,dt_clf.predict(X_test))
print(dt_cm)
print("Accuracy Score:",dt_acc)

[[104   3]
 [  4  60]]
Accuracy Score: 0.9590643274853801


## Random Forest Classification (Best For This Breast Cancer Study)

In [23]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = DecisionTreeClassifier(criterion='entropy',random_state=0)
rf_clf.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [24]:
rf_clf.predict(sc.transform([[8,10,10,8,7,10,9,7,1]]))

array([4], dtype=int64)

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score
rf_cm = confusion_matrix(y_test,rf_clf.predict(X_test))
rf_acc = accuracy_score(y_test,rf_clf.predict(X_test))
print(rf_cm)
print("Accuracy Score:",rf_acc)

[[104   3]
 [  4  60]]
Accuracy Score: 0.9590643274853801
